# Generated by Django 5.1 on 2026-04-19 22:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.CharField(max_length=255, verbose_name='Localisation')),
                ('type', models.CharField(choices=[('STANDARD', 'Standard'), ('COUVERT', 'Couvert'), ('SECURISE', 'Sécurisé')], default='STANDARD', max_length=50, verbose_name='Type')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
                'ordering': ['localisation'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True, verbose_name='Date de réservation')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('lieu_depart', models.CharField(max_length=255, verbose_name='Lieu de départ')),
                ('lieu_retour', models.CharField(max_length=255, verbose_name='Lieu de retour')),
                ('statut_reservation', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant total (MAD)')),
                ('caution_versee', models.BooleanField(default=False, verbose_name='Caution versée')),
                ('nombre_jours', models.IntegerField(default=1, verbose_name='Nombre de jours')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='vehicles.vehicule')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservations.slot')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_reservation'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ACOMPTE', 'Acompte'), ('TOTAL', 'Paiement total'), ('CAUTION', 'Caution'), ('REMBOURSEMENT', 'Remboursement')], default='TOTAL', max_length=20, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (MAD)')),
                ('mode', models.CharField(choices=[('CARTE_BANCAIRE', 'Carte bancaire'), ('ESPECES', 'Espèces'), ('VIREMENT', 'Virement'), ('PAYPAL', 'PayPal')], max_length=20, verbose_name='Mode de paiement')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('COMPLETE', 'Complète'), ('ECHEC', 'Échec'), ('REMBOURSE', 'Remboursé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID Transaction')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LIVRAISON', 'Livraison'), ('RECUPERATION', 'Récupération')], default='LIVRAISON', max_length=20, verbose_name='Type')),
                ('date_livraison', models.DateField(verbose_name='Date')),
                ('heure_livraison', models.TimeField(verbose_name='Heure')),
                ('lieu_livraison', models.CharField(max_length=255, verbose_name='Lieu')),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ECHEC', 'Échec')], default='PLANIFIEE', max_length=20, verbose_name='Statut')),
                ('motif_echec', models.TextField(blank=True, verbose_name="Motif d'échec")),
                ('kilometrage_depart', models.IntegerField(blank=True, null=True, verbose_name='Kilométrage départ')),
                ('kilometrage_retour', models.IntegerField(blank=True, null=True, verbose_name='Kilométrage retour')),
                ('livreur', models.ForeignKey(limit_choices_to={'role': 'LIVREUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-date_livraison'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facture', models.DateTimeField(auto_now_add=True, verbose_name='Date de facture')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant HT (MAD)')),
                ('tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='TVA (%)')),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant TTC (MAD)')),
                ('fichier_pdf', models.FileField(blank=True, upload_to='factures/', verbose_name='Fichier PDF')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='EtatDesLieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=20, verbose_name='Type')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('kilometrage', models.IntegerField(verbose_name='Kilométrage')),
                ('niveau_carburant', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Niveau de carburant (%)')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('photos', models.ImageField(blank=True, upload_to='etat_des_lieux/', verbose_name='Photos')),
                ('signature_client', models.ImageField(blank=True, upload_to='signatures/', verbose_name='Signature client')),
                ('employe', models.ForeignKey(limit_choices_to={'role': 'EMPLOYE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etats_des_lieux', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats_des_lieux', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'État des lieux',
                'verbose_name_plural': 'États des lieux',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('fichier_pdf', models.FileField(blank=True, upload_to='contrats/', verbose_name='Fichier PDF')),
                ('statut_signature', models.CharField(choices=[('GENERE', 'Généré'), ('SIGNE', 'Signé'), ('ANNULE', 'Annulé')], default='GENERE', max_length=20, verbose_name='Statut signature')),
                ('signature_client', models.ImageField(blank=True, upload_to='signatures/', verbose_name='Signature client')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='vehicles.vehicule')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-date'],
                'unique_together': {('client', 'vehicule')},
            },
        ),
    ]
