# Generated by Django 5.1 on 2026-04-27 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        ('vehicles', '0002_alter_document_type_alter_maintenance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etatdeslieux',
            name='niveau_carburant',
            field=models.CharField(choices=[('VIDE', 'Vide'), ('QUART', 'Quart'), ('MOITIE', 'Moitié'), ('TROIS_QUARTS', 'Trois quarts'), ('PLEIN', 'Plein')], default='PLEIN', max_length=20, verbose_name='Niveau de carburant'),
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Mois')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('reservation_count', models.IntegerField(default=0, verbose_name='Nombre de réservations')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revenus (MAD)')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='vehicles.vehicule')),
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
                'ordering': ['-year', '-month'],
                'unique_together': {('vehicule', 'month', 'year')},
            },
        ),
    ]
