# Generated by Django 5.1 on 2026-04-27 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_etatdeslieux_niveau_carburant_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='paiement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture', to='reservations.paiement'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='statut_signature',
            field=models.CharField(choices=[('NON_SIGNE', 'Non signé'), ('SIGNE', 'Signé'), ('ANNULE', 'Annulé')], default='NON_SIGNE', max_length=20, verbose_name='Statut signature'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('LIVREE', 'Livrée'), ('ECHEC', 'Échec')], default='PLANIFIEE', max_length=20, verbose_name='Statut'),
        ),
    ]
