# Generated by Django 5.1 on 2026-04-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_facture_paiement_alter_contrat_statut_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant TVA (MAD)'),
        ),
    ]
