# Generated by Django 4.2.30 on 2026-05-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_add_montant_tva'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='latitude_depart',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude départ'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='latitude_retour',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude retour'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='longitude_depart',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude départ'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='longitude_retour',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude retour'),
        ),
    ]
