# Generated by Django 4.2.30 on 2026-05-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_livraison_latitude_livraison_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('LIVREE', 'Livrée'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
    ]
