# Generated by Django 5.1 on 2026-05-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_livraison_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reference',
            field=models.IntegerField(default=0, verbose_name='Référence client'),
        ),
    ]
