# Generated by Django 5.1 on 2026-05-12 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_add_reference_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='facture',
            name='type',
            field=models.CharField(choices=[('LOCATION', 'Location'), ('PROLONGEMENT', 'Prolongement')], default='LOCATION', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='reservations.reservation'),
        ),
    ]
