# Generated by Django 5.1 on 2026-05-13 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_facture_description_facture_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeProlongation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nouvelle_date_fin', models.DateField(verbose_name='Nouvelle date de fin')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('motif_refus', models.TextField(blank=True, null=True, verbose_name='Motif de refus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_prolongation', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Demande de prolongation',
                'verbose_name_plural': 'Demandes de prolongation',
                'ordering': ['-created_at'],
            },
        ),
    ]
