# Generated by Django 4.2 on 2026-05-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_reservation_delivery_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='type',
            field=models.CharField(choices=[('LIVRAISON', 'Livraison')], default='LIVRAISON', max_length=20, verbose_name='Type'),
        ),
    ]
