# Generated by Django 4.2 on 2026-05-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_alter_livraison_statut_alter_livraison_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='type',
            field=models.CharField(choices=[('LOCATION', 'Location'), ('PROLONGEMENT', 'Prolongement'), ('FRAIS_SUPPLEMENTAIRES', 'Frais supplémentaires')], default='LOCATION', max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type',
            field=models.CharField(choices=[('ACOMPTE', 'Acompte'), ('TOTAL', 'Paiement total'), ('CAUTION', 'Caution'), ('REMBOURSEMENT', 'Remboursement'), ('FRAIS_SUPPLEMENTAIRES', 'Frais supplémentaires')], default='TOTAL', max_length=30, verbose_name='Type'),
        ),
    ]
