# Generated by Django 5.1 on 2026-05-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_alter_facture_type_alter_paiement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Charge ID'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Payment Intent ID'),
        ),
    ]
