# Generated by Django 5.1 on 2026-05-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_paiement_stripe_charge_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='stripe_refund_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Refund ID'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('COMPLETE', 'Complète'), ('EN_ATTENTE_REMBOURSEMENT', 'En attente remboursement'), ('ECHEC', 'Échec'), ('REMBOURSE', 'Remboursé')], default='EN_ATTENTE', max_length=30, verbose_name='Statut'),
        ),
    ]
