# Generated by Django 5.1 on 2026-05-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_paiement_stripe_refund_id_alter_paiement_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Payment Intent ID'),
        ),
    ]
