# Generated by Django 5.1 on 2026-04-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='certifications',
            field=models.TextField(blank=True, verbose_name='Certifications'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='cin',
            field=models.CharField(blank=True, max_length=20, verbose_name='CIN'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, verbose_name='Matricule'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nb_locations',
            field=models.IntegerField(default=0, verbose_name='Nombre de locations'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='niveau_acces',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrateur'), ('ADMIN', 'Administrateur')], default='ADMIN', max_length=20, verbose_name="Niveau d'accès"),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='permis_conduire',
            field=models.CharField(blank=True, max_length=30, verbose_name='Permis de conduire'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='vehicule_service',
            field=models.CharField(blank=True, max_length=50, verbose_name='Véhicule de service'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='zone_couverte',
            field=models.CharField(blank=True, max_length=100, verbose_name='Zone couverte'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
    ]
