# Generated by Django 5.1 on 2026-04-19 22:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100, verbose_name='Marque')),
                ('modele', models.CharField(max_length=100, verbose_name='Modèle')),
                ('annee', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990)], verbose_name='Année')),
                ('immatriculation', models.CharField(max_length=20, unique=True, verbose_name='Immatriculation')),
                ('carburant', models.CharField(choices=[('ESSENCE', 'Essence'), ('DIESEL', 'Diesel'), ('ELECTRIQUE', 'Électrique'), ('HYBRIDE', 'Hybride')], max_length=20, verbose_name='Carburant')),
                ('transmission', models.CharField(choices=[('MANUELLE', 'Manuelle'), ('AUTOMATIQUE', 'Automatique')], max_length=20, verbose_name='Transmission')),
                ('places', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de places')),
                ('couleur', models.CharField(blank=True, max_length=50, verbose_name='Couleur')),
                ('prix_journalier', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix journalier (MAD)')),
                ('caution', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Caution (MAD)')),
                ('kilometrage', models.IntegerField(default=0, verbose_name='Kilométrage')),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('INDISPONIBLE', 'Indisponible'), ('MAINTENANCE_REQUISE', 'Maintenance requise'), ('EN_MAINTENANCE', 'En maintenance'), ('EN_LIVRAISON', 'En livraison')], default='DISPONIBLE', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, upload_to='vehicules/', verbose_name='Photo principale')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='vehicles.categorie')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PREVENTIVE', 'Préventive'), ('CORRECTIVE', 'Corrective'), ('REVISION', 'Révision')], max_length=20, verbose_name='Type')),
                ('date_prevue', models.DateField(verbose_name='Date prévue')),
                ('date_realisee', models.DateField(blank=True, null=True, verbose_name='Date réalisée')),
                ('kilometrage', models.IntegerField(blank=True, null=True, verbose_name='Kilométrage')),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût (MAD)')),
                ('statut', models.CharField(choices=[('MAINTENANCE_REQUISE', 'Maintenance requise'), ('EN_MAINTENANCE', 'En maintenance'), ('TERMINEE', 'Terminée')], default='MAINTENANCE_REQUISE', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('technicien', models.ForeignKey(blank=True, limit_choices_to={'role': 'TECHNICIEN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='vehicles.vehicule')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'ordering': ['-date_prevue'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ASSURANCE', 'Assurance'), ('CARTE_GRISE', 'Carte grise'), ('VISITE_TECHNIQUE', 'Visite technique')], max_length=50, verbose_name='Type')),
                ('numero', models.CharField(max_length=100, verbose_name='Numéro')),
                ('date_emission', models.DateField(blank=True, null=True, verbose_name="Date d'émission")),
                ('date_expiration', models.DateField(verbose_name="Date d'expiration")),
                ('document', models.FileField(blank=True, upload_to='documents/', verbose_name='Document')),
                ('alert_envoyee', models.BooleanField(default=False, verbose_name='Alerte envoyée')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicule')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['date_expiration'],
            },
        ),
        migrations.CreateModel(
            name='VehiculePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='vehicules/', verbose_name='Photo')),
                ('titre', models.CharField(blank=True, max_length=100, verbose_name='Titre')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='vehicles.vehicule')),
            ],
            options={
                'verbose_name': 'Photo du véhicule',
                'verbose_name_plural': 'Photos des véhicules',
            },
        ),
    ]
