# Generated by Django 5.1 on 2026-04-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('CARTE_GRISE', 'Carte grise'), ('ASSURANCE', 'Assurance'), ('VISITE_TECHNIQUE', 'Visite technique'), ('VIGNETTE', 'Vignette')], max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='type',
            field=models.CharField(choices=[('VIDANGE', 'Vidange'), ('REVISION', 'Révision'), ('REPARATION', 'Réparation'), ('CONTROLE_TECHNIQUE', 'Contrôle technique'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type'),
        ),
    ]
